src/Mango/PlatformBundle/Entity/Image.php
<?php

namespace Mango\PlatformBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Image
 *
 * @ORM\Table(name="mango_image")
 * @ORM\Entity(repositoryClass="Mango\PlatformBundle\Repository\ImageRepository")
 * @ORM\HasLifecycleCallbacks
 */
class Image
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="url", type="string", length=255)
     * 
     */
    private $url;

    /**
     * @var string
     *
     * @ORM\Column(name="alt", type="string", length=255)
     */
    private $alt;

    /**
    * @Assert\File(
    *   mimeTypes = {"image/jpeg", "image/jpg", "image/png"},
    *   mimeTypesMessage = "Veuillez sélectionner une image au format .jpg ou .png",
    *   maxSize = "500k",
    *   maxSizeMessage = "Le poids de votre image est trop important (<500ko)"
    *)
    */
    private $file;

    private $tempFilename; //Temporaire
  
    public function getFile()
    {
        return $this->file;
    }

    public function setFile(UploadedFile $file)
    {
        $this->file = $file;

        // On vérifie si on avait déjà un fichier pour cette entité
        if (null !== $this->url) {
            // On sauvegarde l'extension du fichier pour le supprimer plus tard
            $this->tempFilename = $this->url;

            // On réinitialise les valeurs des attributs url et alt
            $this->url = null;
            $this->alt = null;
        }
    }

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set url
     *
     * @param string $url
     *
     * @return image
     */
    public function setUrl($url)
    {
        $this->url = $url;

        return $this;
    }

    /**
     * Get url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Set alt
     *
     * @param string $alt
     *
     * @return image
     */
    public function setAlt($alt)
    {
        $this->alt = $alt;

        return $this;
    }

    /**
     * Get alt
     *
     * @return string
     */
    public function getAlt()
    {
        return $this->alt;
    }

    /**
   * @ORM\PrePersist()
   * @ORM\PreUpdate()
   */
  public function preUpload()
  {
    // Si jamais il n'y a pas de fichier (champ facultatif), on ne fait rien
    if (null === $this->file) {
      return;
    }

    // Le nom du fichier est son id, on doit juste stocker également son extension
    // Pour faire propre, on devrait renommer cet attribut en « extension », plutôt que « url »
    $this->url = $this->file->guessExtension();

    // Et on génère l'attribut alt de la balise <img>, à la valeur du nom du fichier sur le PC de l'internaute
    $this->alt = $this->file->getClientOriginalName();
  }

    /**
    * @ORM\PostPersist()
    * @ORM\PostUpdate()
    */
    public function upload()
    {
        // Si jamais il n'y a pas de fichier (champ facultatif), on ne fait rien
        if (null === $this->file) {
            return;
        }

        // Si on avait un ancien fichier, on le supprime
        if (null !== $this->tempFilename) {
          $oldFile = $this->getUploadRootDir().'/'.$this->id.'.'.$this->tempFilename;
          if (file_exists($oldFile)) {
            unlink($oldFile);
          }
        }

        // On déplace le fichier envoyé dans le répertoire de notre choix
        $this->file->move(
          $this->getUploadRootDir(), // Le répertoire de destination
          $this->id.'.'.$this->url   // Le nom du fichier à créer, ici « id.extension »
        );
    }

    /**
    * @ORM\PreRemove()
    */
    public function preRemoveUpload()
    {
        // On sauvegarde temporairement le nom du fichier, car il dépend de l'id
        $this->tempFilename = $this->getUploadRootDir().'/'.$this->id.'.'.$this->url;
    }

    /**
    * @ORM\PostRemove()
    */
    public function removeUpload()
    {
        // En PostRemove, on n'a pas accès à l'id, on utilise notre nom sauvegardé
        if (file_exists($this->tempFilename)) {
          // On supprime le fichier
          unlink($this->tempFilename);
        }
    }

    public function getUploadDir()
    {
        // On retourne le chemin relatif vers l'image pour un navigateur
        return 'img/photo';
    }

    protected function getUploadRootDir()
    {
        // On retourne le chemin relatif vers l'image pour notre code PHP
        return __DIR__.'/../../../../web/'.$this->getUploadDir();
    }

    public function getWebPath() //Simplification de la vue twig pour l'image
    {
        return $this->getUploadDir().'/'.$this->getId().'.'.$this->getUrl();
    }
}

src/Mango/PlatformBundle/Form/RentType.php
<?php

namespace Mango\PlatformBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormInterface;
use Mango\PlatformBundle\Entity\Region;
use Mango\PlatformBundle\Entity\Departement;


class RentType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title',     TextType::class)
            ->add('price', IntegerType::class)
            ->add('charge', IntegerType::class)
            ->add('size', IntegerType::class)
            ->add('nbParts', IntegerType::class)
            ->add('userId',    HiddenType::class)
            ->add('content',   TextareaType::class)
            ->add('image',     ImageType::class, array(
                    'required'     => false
            ))
            ->add('type', EntityType::class, array(    //Permet de faire un <select>
                    'class'        => 'MangoPlatformBundle:Type',
                    'placeholder'  => 'Sélectionnez le type de bien',
                    'choice_label' => 'name',
                    'multiple'     => false,
            ))
            ->add('region', EntityType::class, array(   
                    'class'        => 'MangoPlatformBundle:Region',
                    'placeholder'  => 'Sélectionnez votre région',
                    'choice_label' => 'name',
                    'multiple'     => false,
            ))

            ->get('region')->addEventListener(
                FormEvents::POST_SUBMIT,
                function(FormEvent $event){
                    $form = $event->getForm();
                    $this-> addDepartementField($form->getParent(), $form->getData()); //Appel la méthode pour construire l'input departement   
                }
            );

        $builder->addEventListener(        //Pour l'édition
              FormEvents::POST_SET_DATA,
              function (FormEvent $event) {
                $data = $event->getData();
                $ville = $data->getCity();
                $form = $event->getForm();
                if ($ville) {
                  // On récupère le département et la région
                  $departement = $ville->getDepartement();
                  $region = $departement->getRegion();
                  // On crée les 2 champs supplémentaires
                  $this->addDepartementField($form, $region);
                  $this->addCityField($form, $departement);
                  // On set les données
                  $form->get('region')->setData($region);
                  $form->get('departement')->setData($departement);
                }else {
                    // On crée les 2 champs en les laissant vide (champs utilisé pour le JavaScript)
                    $this->addDepartementField($form, null);
                    $this->addCityField($form, null);
                }
            }
        );
    }

   private function addDepartementField(FormInterface $form, ?Region $region)
    {
      $builder = $form->getConfig()->getFormFactory()->createNamedBuilder(
        'departement',
        EntityType::class,
        null,
        [
          'class'           => 'MangoPlatformBundle:Departement',
          'placeholder'     => $region ? 'Sélectionnez votre département' : 'Veuillez sélectionnez une région avant',
          'auto_initialize' => false,
          'choices'         => $region ? $region->getDepartements() : []
        ]
      );

      $builder->addEventListener(
        FormEvents::POST_SUBMIT,
        function (FormEvent $event) {
          $form = $event->getForm();
          $this->addCityField($form->getParent(), $form->getData());
        }
      );

      $form->add($builder->getForm());
    }

    private function addCityField(FormInterface $form, ?Departement $departement)
    {
        $builder = $form->getConfig()->getFormFactory()->createNamedBuilder(
            'city',
            EntityType::class,
            null,
            [
              'class'           => 'MangoPlatformBundle:City',
              'placeholder'     => $departement ? 'Sélectionnez votre ville' : 'Veuillez sélectionnez un département avant',
              'auto_initialize' => false,
              'choices'         => $departement ? $departement->getCities() : []
            ]
          );
          
          $form->add($builder->getForm());
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Mango\PlatformBundle\Entity\Rent'   //Définition de l'objet en lien avec le formulaire
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'mango_platformbundle_rent';
    }
}

src/Mango/PlatformBundle/Controller/RentController.php
<?php
namespace Mango\PlatformBundle\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;

class RentController extends Controller
{
    public function indexRentAction($page)  //Afffichage page des annonces de vente
    {
        $active = "louer";
        $nbPerPage = 8;
        $listRents = $this->getDoctrine()   
                            ->getManager()
                            ->getRepository('MangoPlatformBundle:Rent')
                            ->getRents($page, $nbPerPage);  //Récupère toutes les annonces

        $nbPages = ceil(count($listRents)/$nbPerPage); //calcul du nb de page à afficher pour la pagination

        if($page>$nbPages){
            throw new NotFoundHTTPException("La page " . $page . " d'annonces n'existe pas");
        }
        return $this->render('MangoPlatformBundle:Rent:index.html.twig', array('listRents' => $listRents, 'nbPages'=>$nbPages, 'page'=>$page, 'active' => $active));
    }

    public function viewAction($id)
    {
        $active = "louer";
    	$em = $this->getDoctrine()->getManager(); //Enclenche les processus de Doctrine pour les entités 

        $rent = $em->getRepository('MangoPlatformBundle:Rent')->find($id); //Récupération de l'objet Rent en fonction de son id
        $userId = $rent->getUserId();
        $user = $em->getRepository('UserBundle:User')->find($userId); //Récupération de l'objet User

        if(null===$rent){
            throw new NotFoundHttpException("Désolé, l'annonce n°" . $id . " n'existe pas");
        }
    	return $this->render('MangoPlatformBundle:Rent:view.html.twig', array('rent' => $rent, 'user' => $user, 'active' => $active));
    }

}

src/Mango/PlatformBundle/Resources/views/Rent/index.html.twig
{% extends "::layout.html.twig" %}

{% block title %}
  Louer - {{ parent()}}
{% endblock %}

{% block body %}
	<section class="index-advert">
		<h1 class="row">Louer</h1>
		<ul class="row justify-content-md-center justify-content-lg-start">

			{% for rent in listRents %} {# Affichage des annonces #}
			    <li class="advert col-12 col-md-6 col-lg-3">
			      	<a href="{{ path('mango_platform_rent_view', {'id':rent.id}) }}">
			      		<div class="cover">
			      			<img src="{{ asset(rent.image.webPath) }}" alt="{{ rent.image.alt }}" class="img-fluid" />
			      		</div>
			      		<div class="row cover-text">
			      			<p class="col-6 city">{{ rent.city.name }} ({{ rent.city.zipcode }})</p>
			      			<p class="col-6 text-right date">{{ rent.date|date('d/m/Y') }}</p>
				      		<h3 class="col-12 title">{{ rent.title }}</h3>
				      		<p class="col-12 type">{{ rent.type.name }} | {{ rent.size }} m² {% if rent.meuble == 1 %}| meublé{% elseif rent.collocation == 1 %}| collocation{% endif %}</p>
				      		<p class="col-12 text-right price">{{ rent.price }} €</p>
			      		</div>
			      	</a> 
			    </li>
		    {% else %}
		      <li>Votre bonheur n'est pas encore disponible, veuillez nous excuser</li>
		    {% endfor %}

		</ul>
		<!-- Pagination -->
		{% if nbPages > 1 %} {# si une seule page pas besoin de pagination #}
			<nav aria-label="navigation page location">
				<ul class="pagination justify-content-center">

					{% if page != 1 %} {# si on est sur la première page pas besoin de retour en arrière #}
						<li class="page-item">
						   	<a class="page-link" href="{{ path('mango_platform_rent', {'page': page-1}) }}" aria-label="Previous">
						        <span aria-hidden="true">&laquo;</span>
						        <span class="sr-only">Précédent</span>
						    </a>
						</li>
					{% endif %}

					{% for p in range(1, nbPages) %}
						<li class="page-item {% if p == page %} active {% endif %}">
					      <a href="{% if p == page %} # {% else %}{{ path('mango_platform_buy', {'page': p}) }} {% endif %}" class="page-link">{{ p }}</a>
					    </li>
					{% endfor %}

					{% if page+1 <= nbPages %} {# si on est sur la dernière page pas besoin de bouton avancer #}
						<li class="page-item">
					      <a class="page-link" href="{{ path('mango_platform_rent', {'page': page+1}) }}" aria-label="Next">
					        <span aria-hidden="true">&raquo;</span>
					        <span class="sr-only">Suivant</span>
					      </a>
					    </li>
					{% endif %}

				</ul>
			</nav>
		{% endif %}
	</section>
{% endblock %} 

src/Mango/PlatformBundle/Resources/views/Rent/view.html.twig
{% extends "::layout.html.twig" %}

{% block title %}
  {{ rent.title }} - {{ parent()}}
{% endblock %}

{% block body %}
	<section class="view">
		<h1>Louer</h1>
		{% if rent.published != 0 %}
			<h2>{{ rent.title }}</h2>
			<article class="row">
				<div class="col-12 col-lg-4">
					<img src="{{ asset(rent.image.webPath) }}" alt="{{ rent.image.alt }}" class="img-fluid" />
				</div>
				<div class="col-12 col-lg-8">
					<div class="row">
						<div class="col-12 col-lg-4">
							<p><span>Localisation : </span>{{ rent.city.name }} ({{ rent.city.zipcode }})</p>
							<p><span>Type de bien : </span>{{ rent.type.name }}</p>
							<p><span>Prix : </span>{{ rent.price }} €/mois | <span>Charges :</span> {{ rent.charge }}</p>
							<p><span>Superficie : </span>{{ rent.size }} m²</p>
							<p><span>Nombre de pièces : </span>{{ rent.nbParts }} pièces</p>
							<p><span>Meublé: </span>{% if rent.meuble == 1 %} Oui {% else %} Non {% endif %}</p>
							<p><span>Collocation: </span>{% if rent.collocation == 1 %} Oui {% else %} Non {% endif %}</p>
						</div>
						<div class="col-12 col-lg-8">
							<iframe width="100%" height="300" frameborder="0" style="border:0"
							src="https://www.google.com/maps/embed/v1/place?q={{ rent.city.name }}&key=AIzaSyBQFyvNGExyTQBLYbOIpyzmD7fBhLMmlx4" allowfullscreen></iframe>
						</div>
					</div>
					<div class="row description">
						<div class="col-12">
							<p><span>Description</span></p>
							<p>{{ rent.content }}</p>
							<p class="col-12 text-right"><span>Proposé par : </span>{{user.username}}</p>

							{% if not is_granted('ROLE_USER') %}
								<div class="text-right">
									<a href="#" class="btn col-12 col-md-4 contact">Contacter   <span class="fas fa-address-book"></span></a>
								</div>
							{% else %}
								<form class="text-right" action="">
									{# Bouton pour afficher le mail #}
									<button class="btn col-12 col-md-4" type="button" id='btn-mail-rent'>Voir le mail   <span class="fas fa-envelope"></span></button>
									
									{# si l'annonceur a renseigné son numéro de tél #}
									{% if user.phone is not null %}
										{# Bouton pour l'affichage du numéro #}
										<button class="btn col-12 col-md-4" type="button" id='btn-tel-rent'>Voir le n° de téléphone   <span class="fas fa-phone"></span></button>
									{% endif %}

									<input type="hidden" name="userId" id="user-id" value='{{ user.id }}'/>
									<input type="hidden" name="nbAdvert" id="nbAdvert" value='{{ rent.id }}'/>
								</form>
							{% endif %} 
						</div>
					</div>
				</div>
			</article>
		{% else %}
			<p>Désolé cette annonce n'est pas encore disponible</p>
		{% endif %}
		<a href="{{ path('mango_platform_rent', {'page': 1}) }}" class="btn retour col-12 col-lg-2">Retourner aux annonces</a>
	</section>
{% endblock %}